<?php
  return  [
        [
            'type' => 'link',
            'title' => 'Dashboard',
            'icon' => 'fa-solid fa-gauge',
            'route' => 'admin.dashboard',
            'active' => 'admin.dashboard',
            'can'=> ['access_dashboard'],
        ],
        [
            'type' => 'header',
            'title' => 'Gestión',
            'can'=>[
                'read_role',
                'read_user',
                'read_patient',
                'read_socialwork',
                'access_speciality',
                'read_cabinet',
                'read_appointment',
                'read_calendar',
            ],
        ],
        [
            'type' => 'link',
            'title' => 'Roles y permisos',
            'icon' => 'fa-solid fa-shield-halved',
            'route' => 'admin.roles.index',
            'active' => 'admin.roles.*',
            'can'=>['read_role'],


        ],

        [
            'type' => 'link',
            'title' => 'Usuarios',
            'icon' => 'fa-solid fa-users',
            'route' => 'admin.users.index',
            'active' =>'admin.users.*',
            'can'=> ['read_user'],
         ],
        [
            'type' => 'link',
            'title' => 'Pacientes',
            'icon' => 'fa-solid fa-user-injured',
            'route' => 'admin.patients.index',
            'active' => 'admin.patients.*',
            'can' => ['read_patient'],
        ],
         [
            'type' => 'link',
             'title' => 'obras sociales',
             'icon' => 'fa-solid fa-hand-holding-medical',
             'route' => 'admin.socialworks.index',
             'active' => 'admin.socialworks.*',
             'can' => ['read_socialwork'],
        ],
        [
            'type' => 'link',
            'title' => 'Especialidades',
            'icon' => 'fa-solid fa-stethoscope',
            'route' => 'admin.specialities.index',
            'active' => 'admin.specialities.*',
            'can' => ['access_speciality'],
        ],
            [
                'type' => 'link',
                'title' => 'Doctores',
                'icon' => 'fa-solid fa-user-doctor',
                'route' => 'admin.doctors.index',
                'active' =>'admin.doctors.*',
            'can'=>['read_doctor'],
        ],
        [
            'type' => 'link',
            'title' => 'Gabinetes',
            'icon' => 'fa-solid fa-door-open',
            'route' => 'admin.cabinets.index',
            'active' =>'admin.cabinets.*',
            'can'=>['read_cabinet'],
        ],
        [
            'type' => 'link',
            'title' => 'Turnos',
            'icon' => 'fa-solid fa-calendar-check',
            'route' => 'admin.appointments.index',
            'active' => 'admin.appointments.*',
            'can'=> ['read_appointment'],
        ],
        [
            'type' => 'link',
            'title' => 'Calendario',
            'icon' => 'fa-solid fa-calendar-days',
            'route' => 'admin.calendar.index',
            'active' =>'admin.calendar.*',
            'can'=> ['read_calendar'],
        ],
        [
            'type' => 'link',
            'title' => 'Períodos de Bloqueo',
            'icon' => 'fa-solid fa-ban',
            'route' => 'admin.unavailability.index',
            'active' =>'admin.unavailability.*',
            'can'=> ['read_doctor'],
        ],
    ];
